name: Arta Wiguna
description: Welcome to my Blog
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "https://arta678.github.io/"
# google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]


# Details for the RSS feed generator
url: ""
author: "Arta W"

# Disqus config
disqus-shortname: ""
